-- LevelConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class LevelConfig
---@field Data table<string, table>

---@type LevelConfig
local LevelConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
LevelConfig.Data = {
 
}
-- --- AUTO GENERATED CONFIG END ---

return LevelConfig
